"use client";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";

export default function NewTask(){
 const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [category,setCategory]=useState("GENERAL");const [reward,setReward]=useState("");const [url,setUrl]=useState("");const [maxWorkers,setMaxWorkers]=useState("");const [deadline,setDeadline]=useState("");const [requirements,setRequirements]=useState("Provide proof of completion");
 const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");const req=requirements.split("\n").map(x=>x.trim()).filter(Boolean).map((x,i)=>({title:"Requirement "+(i+1),description:x}));const {data,error}=await createClient().rpc("admin_create_task",{p_title:title,p_description:description,p_category:category,p_reward_amount:Number(reward),p_currency:"NGN",p_target_url:url||null,p_max_workers:maxWorkers?Number(maxWorkers):null,p_deadline:deadline?new Date(deadline).toISOString():null,p_completion_window_hours:null,p_requirements:req});if(error){setError(error.message);setBusy(false);return;}if(!data) throw new Error("TASK_CREATE_FAILED"); const {error:publishError}=await createClient().rpc("admin_publish_task",{p_task_id:data}); if(publishError) throw publishError; router.push("/admin/tasks");}
 const router=useRouter();
 return <main className="shell"><header className="topbar"><div><span className="eyebrow">ADMIN</span><h1>Create task</h1></div><a className="button" href="/admin/tasks">Back</a></header><form className="card form" onSubmit={submit}><label>Title<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Description<textarea required rows={6} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="grid"><label>Category<input required value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Reward (NGN)<input required type="number" min="0" step="0.01" value={reward} onChange={e=>setReward(e.target.value)}/></label><label>Maximum workers<input type="number" min="1" value={maxWorkers} onChange={e=>setMaxWorkers(e.target.value)}/></label><label>Deadline<input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label></div><label>Target URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)}/></label><label>Requirements (one per line)<textarea rows={5} value={requirements} onChange={e=>setRequirements(e.target.value)}/></label>{error&&<p className="notice">{error}</p>}<button className="button primary" disabled={busy}>{busy?"Creating…":"Create & publish"}</button></form></main>;
}